# Generated by Django 4.2.4 on 2023-08-17 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "设备参数", "verbose_name_plural": "设备参数"},
        ),
    ]
