# Generated by Django 4.2.4 on 2023-08-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0003_alter_equipment_purchase_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="设备型号"
            ),
        ),
    ]
