# Generated by Django 4.2.4 on 2023-09-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_info', '0007_alter_equipment_current_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='current_value',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='设备现价值'),
        ),
    ]
