# Generated by Django 4.2.4 on 2023-09-22 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0009_delete_equipment2_equipment_update_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "设备参数", "verbose_name_plural": "设备参数"},
        ),
    ]
