# Generated by Django 4.2.4 on 2023-10-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0010_alter_equipment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=200, verbose_name="采购品类")),
                (
                    "manufacturing_process",
                    models.CharField(max_length=200, verbose_name="制造工艺"),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=200, verbose_name="设备名称"),
                ),
                (
                    "equipment_model",
                    models.CharField(max_length=200, verbose_name="设备型号"),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="设备现价值"
                    ),
                ),
                (
                    "remaining_depreciation_years",
                    models.IntegerField(verbose_name="剩余折旧年数"),
                ),
                (
                    "power_kw",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="设备功率"
                    ),
                ),
                (
                    "auxiliary_power_a_kw",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="辅助设备A功率"
                    ),
                ),
                (
                    "auxiliary_power_b_kw",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="辅助设备B功率"
                    ),
                ),
                (
                    "auxiliary_power_c_kw",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="辅助设备C功率"
                    ),
                ),
                (
                    "water_consumption",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="耗水量"
                    ),
                ),
                (
                    "gas_consumption",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="耗气量"
                    ),
                ),
                (
                    "other_resource_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="其他资源名称"
                    ),
                ),
                (
                    "other_resource_unit",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="其他资源单位"
                    ),
                ),
                (
                    "other_resource_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="其他资源耗用量",
                    ),
                ),
                (
                    "other_resource_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="其他资源单价",
                    ),
                ),
                (
                    "additional_resource_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="附加资源名称"
                    ),
                ),
                (
                    "additional_resource_unit",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="附加资源单位"
                    ),
                ),
                (
                    "additional_resource_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="附加资源耗用量",
                    ),
                ),
                (
                    "additional_resource_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="附加资源单价",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备参数(详细)",
                "verbose_name_plural": "设备参数(详细)",
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "设备参数(润滑油)", "verbose_name_plural": "设备参数（润滑油）"},
        ),
    ]
