# Generated by Django 4.2.4 on 2023-10-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0012_alter_equipment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment2",
            options={"verbose_name": "设备参数", "verbose_name_plural": "设备参数"},
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="additional_resource_consumption",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="附加资源耗用量",
            ),
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="additional_resource_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="附加资源单价",
            ),
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="auxiliary_power_a_kw",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="辅助设备A功率"
            ),
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="auxiliary_power_b_kw",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="辅助设备B功率"
            ),
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="auxiliary_power_c_kw",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="辅助设备C功率"
            ),
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="gas_consumption",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="耗气量"
            ),
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="other_resource_consumption",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="其他资源耗用量",
            ),
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="other_resource_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="其他资源单价",
            ),
        ),
        migrations.AlterField(
            model_name="equipment2",
            name="water_consumption",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="耗水量"
            ),
        ),
    ]
