# Generated by Django 4.2.4 on 2023-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0013_alter_equipment2_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="equipment2",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
