# Generated by Django 4.2.4 on 2023-10-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0014_equipment_notes_equipment2_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment2",
            name="update_date",
            field=models.DateField(auto_now=True, null=True, verbose_name="更新日期"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="update_date",
            field=models.DateField(auto_now=True, null=True, verbose_name="价格更新日期"),
        ),
    ]
