# Generated by Django 4.2.4 on 2023-10-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "equipment_info",
            "0022_alter_equipment2_additional_resource_consumption_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Equipment2",
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "设备参数", "verbose_name_plural": "设备参数"},
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="lubricating_oil_consumption",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="oil_price_per_kg",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="purchase_category",
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="附加资源耗用量",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="附加资源名称"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="附加资源单价",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_unit",
            field=models.CharField(
                blank=True, default=0, max_length=200, null=True, verbose_name="附加资源单位"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="auxiliary_power_a_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="辅助设备A功率",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="auxiliary_power_b_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="辅助设备B功率",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="auxiliary_power_c_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="辅助设备C功率",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                choices=[
                    ("塑料成品", "塑料成品"),
                    ("注塑", "注塑"),
                    ("喷涂", "喷涂"),
                    ("电镀", "电镀"),
                    ("烫金", "烫金"),
                    ("印刷", "印刷"),
                    ("喷绘", "喷绘"),
                    ("组装", "组装"),
                    ("冲压", "冲压"),
                    ("抛光", "抛光"),
                    ("氧化", "氧化"),
                    ("酸洗", "酸洗"),
                    ("刻字", "刻字"),
                    ("磁铁", "磁铁"),
                    ("垂重", "垂重"),
                    ("弹簧", "弹簧"),
                    ("铝件成品", "铝件成品"),
                    ("栈板", "栈板"),
                    ("纸箱/纸板", "纸箱/纸板"),
                    ("包装袋", "包装袋"),
                    ("彩盒", "彩盒"),
                    ("吸塑盘", "吸塑盘"),
                    ("转印纸", "转印纸"),
                    ("垫片", "垫片"),
                    ("箔纸", "箔纸"),
                    ("标签", "标签"),
                    ("收缩膜", "收缩膜"),
                    ("模架", "模架"),
                    ("模芯", "模芯"),
                    ("玻璃管", "玻璃管"),
                    ("棉头", "棉头"),
                    ("镜片", "镜片"),
                    ("胶头", "胶头"),
                    ("刷毛", "刷毛"),
                ],
                default="new",
                max_length=200,
                verbose_name="采购品类",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="gas_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="耗气量",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="other_resource_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="其他资源耗用量",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="other_resource_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="其他资源名称"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="other_resource_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="其他资源单价",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="other_resource_unit",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="其他资源单位"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="water_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="耗水量",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="current_value",
            field=models.DecimalField(
                decimal_places=2, default="0", max_digits=10, verbose_name="设备现价值"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_model",
            field=models.CharField(max_length=200, verbose_name="设备型号"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_name",
            field=models.CharField(default="new", max_length=200, verbose_name="设备名称"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equipment",
            name="manufacturing_process",
            field=models.CharField(max_length=200, verbose_name="制造工艺"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="power_kw",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="设备功率"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="update_date",
            field=models.DateField(auto_now=True, null=True, verbose_name="更新日期"),
        ),
    ]
