# Generated by Django 4.2.4 on 2023-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0024_alter_equipment_auxiliary_power_a_kw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="auxiliary_power_a_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="辅助设备A功率",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="auxiliary_power_b_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="辅助设备B功率",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="auxiliary_power_c_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="辅助设备C功率",
            ),
        ),
    ]
