# Generated by Django 4.2.4 on 2023-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0025_alter_equipment_auxiliary_power_a_kw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_consumption2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="附加资源耗用量2",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_consumption3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="附加资源耗用量3",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_name2",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="附加资源名称2"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_name3",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="附加资源名称3"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_price2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="附加资源单价2",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_price3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="附加资源单价3",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_unit2",
            field=models.CharField(
                blank=True, default=0, max_length=200, null=True, verbose_name="附加资源单位2"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="additional_resource_unit3",
            field=models.CharField(
                blank=True, default=0, max_length=200, null=True, verbose_name="附加资源单位3"
            ),
        ),
    ]
