# Generated by Django 4.2.4 on 2023-10-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_info", "0028_alter_equipment_equipment_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="update_date",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="更新日期"
            ),
        ),
    ]
