# Generated by Django 4.2.4 on 2023-11-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备名称')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备型号')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_fee', models.FloatField(blank=True, null=True, verbose_name='管理费用')),
                ('profit_margin', models.FloatField(blank=True, null=True, verbose_name='利润率')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='材料名称')),
                ('grade', models.CharField(blank=True, max_length=255, null=True, verbose_name='材料牌号')),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='标准包装数量')),
                ('size_length', models.FloatField(blank=True, null=True, verbose_name='标准包装尺寸长')),
                ('size_width', models.FloatField(blank=True, null=True, verbose_name='标准包装尺寸宽')),
                ('size_height', models.FloatField(blank=True, null=True, verbose_name='标准包装尺寸高')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='厂商名字')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商代码')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='生产地点')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='目的地')),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='提货地')),
                ('shipping_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='出货方式')),
                ('transport_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='运输方式')),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='运输车型')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='运输距离')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='类别')),
                ('purchase_part', models.CharField(blank=True, max_length=255, null=True, verbose_name='采购零件')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='零件编号')),
                ('size_length', models.FloatField(blank=True, null=True, verbose_name='零件尺寸长')),
                ('size_width', models.FloatField(blank=True, null=True, verbose_name='零件尺寸宽')),
                ('size_thickness', models.FloatField(blank=True, null=True, verbose_name='零件尺寸厚度')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='零件立方')),
                ('manufacturing_process', models.CharField(blank=True, max_length=255, null=True, verbose_name='制造工艺')),
                ('requires_mold', models.BooleanField(blank=True, null=True, verbose_name='需要模具')),
                ('cavities_per_mold', models.IntegerField(blank=True, null=True, verbose_name='穴数/模')),
                ('material_utilization', models.FloatField(blank=True, null=True, verbose_name='材料利用率')),
                ('recycle_usage_rate', models.FloatField(blank=True, null=True, verbose_name='回料使用率')),
                ('production_cycle', models.FloatField(blank=True, null=True, verbose_name='生产周期')),
                ('operator_count', models.IntegerField(blank=True, null=True, verbose_name='操作员数量')),
                ('min_order_quantity', models.IntegerField(blank=True, null=True, verbose_name='最小起订量')),
                ('annual_demand', models.IntegerField(blank=True, null=True, verbose_name='年需求量')),
                ('equipments', models.ManyToManyField(blank=True, to='product.equipment', verbose_name='设备')),
                ('finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.finance', verbose_name='财务')),
                ('materials', models.ManyToManyField(blank=True, to='product.material', verbose_name='材料')),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.packaging', verbose_name='包装')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.supplier', verbose_name='供应商')),
                ('transportation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.transportation', verbose_name='运输')),
            ],
        ),
    ]
