# Generated by Django 4.2.4 on 2023-11-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_price_info', '0015_alter_materialprice_price_update_date'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AlterField(
            model_name='part',
            name='materials',
            field=models.ManyToManyField(blank=True, to='material_price_info.materialprice', verbose_name='材料'),
        ),
    ]
