# Generated by Django 4.2.4 on 2023-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cost_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("产品描述", models.TextField(blank=True, null=True)),
                ("公式", models.TextField(blank=True, null=True)),
                ("参与方式", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Cost",
        ),
        migrations.DeleteModel(
            name="Process",
        ),
    ]
