# Generated by Django 4.2.4 on 2023-08-24 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cost_analysis", "0002_costanalysis_delete_cost_delete_process"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costanalysis",
            options={"verbose_name": "垂重成本计算", "verbose_name_plural": "垂重成本计算"},
        ),
    ]
