# Generated by Django 4.2.4 on 2023-09-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_analysis', '0004_processingmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingmethod',
            options={'verbose_name': '加工方法表', 'verbose_name_plural': '加工方法表'},
        ),
        migrations.RenameField(
            model_name='processingmethod',
            old_name='name',
            new_name='加工方法',
        ),
    ]
