# Generated by Django 4.2.4 on 2023-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_analysis', '0005_alter_processingmethod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('产品编号', models.CharField(max_length=255)),
                ('材料费', models.FloatField(blank=True, null=True)),
                ('加工费', models.FloatField(blank=True, null=True)),
                ('运输费', models.FloatField(blank=True, null=True)),
                ('包装费', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '计算历史',
                'verbose_name_plural': '计算历史',
            },
        ),
    ]
