# Generated by Django 4.2.4 on 2023-09-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_analysis', '0006_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='利润率',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='总成本',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='管理费比例',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
