# Generated by Django 4.2.4 on 2023-09-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_analysis', '0007_record_利润率_record_总成本_record_管理费比例'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostAnalysis',
        ),
    ]
