# Generated by Django 4.2.4 on 2023-09-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_analysis', '0008_delete_costanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='加工明细',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
