# Generated by Django 4.2.4 on 2023-09-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_analysis', '0009_record_加工明细'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessingMethod',
        ),
    ]
