# Generated by Django 4.2.4 on 2023-08-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="材料名称"),
                ),
                (
                    "material_grade",
                    models.CharField(max_length=100, verbose_name="材料牌号"),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=50, verbose_name="计量单位"),
                ),
                (
                    "pricing_currency",
                    models.CharField(max_length=50, verbose_name="计价货币"),
                ),
                ("price", models.FloatField(verbose_name="价格")),
                ("scrap_price", models.FloatField(verbose_name="废料价格")),
                ("price_update_date", models.DateField(verbose_name="价格更新日期")),
            ],
            options={
                "verbose_name": "材料价格",
                "verbose_name_plural": "材料价格",
            },
        ),
    ]
