# Generated by Django 4.2.4 on 2023-08-24 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("material_price_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialprice",
            options={"verbose_name": "垂重材料价格", "verbose_name_plural": "垂重材料价格"},
        ),
    ]
