# Generated by Django 4.2.4 on 2023-09-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_price_info', '0006_diandumaterialprice_pentumaterialprice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialPrice',
            new_name='ChuizhongMaterialPrice',
        ),
    ]
