# Generated by Django 4.2.4 on 2023-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material_price_info", "0007_rename_materialprice_chuizhongmaterialprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChongyangMaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=100, verbose_name="供应商名称"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="材料名称"),
                ),
                (
                    "material_grade",
                    models.CharField(max_length=100, verbose_name="材料牌号"),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=50, verbose_name="计量单位"),
                ),
                (
                    "pricing_currency",
                    models.CharField(max_length=50, verbose_name="计价货币"),
                ),
                ("price", models.FloatField(verbose_name="价格")),
                ("scrap_price", models.FloatField(verbose_name="废料价格")),
                ("price_update_date", models.DateField(verbose_name="价格更新日期")),
            ],
            options={
                "verbose_name": "冲压材料价格",
                "verbose_name_plural": "冲压材料价格",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PenhuiMaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=100, verbose_name="供应商名称"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="材料名称"),
                ),
                (
                    "material_grade",
                    models.CharField(max_length=100, verbose_name="材料牌号"),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=50, verbose_name="计量单位"),
                ),
                (
                    "pricing_currency",
                    models.CharField(max_length=50, verbose_name="计价货币"),
                ),
                ("price", models.FloatField(verbose_name="价格")),
                ("scrap_price", models.FloatField(verbose_name="废料价格")),
                ("price_update_date", models.DateField(verbose_name="价格更新日期")),
            ],
            options={
                "verbose_name": "喷绘材料价格",
                "verbose_name_plural": "喷绘材料价格",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QiegeMaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=100, verbose_name="供应商名称"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="材料名称"),
                ),
                (
                    "material_grade",
                    models.CharField(max_length=100, verbose_name="材料牌号"),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=50, verbose_name="计量单位"),
                ),
                (
                    "pricing_currency",
                    models.CharField(max_length=50, verbose_name="计价货币"),
                ),
                ("price", models.FloatField(verbose_name="价格")),
                ("scrap_price", models.FloatField(verbose_name="废料价格")),
                ("price_update_date", models.DateField(verbose_name="价格更新日期")),
            ],
            options={
                "verbose_name": "切割材料价格",
                "verbose_name_plural": "切割材料价格",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZuzhuangMaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=100, verbose_name="供应商名称"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="材料名称"),
                ),
                (
                    "material_grade",
                    models.CharField(max_length=100, verbose_name="材料牌号"),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=50, verbose_name="计量单位"),
                ),
                (
                    "pricing_currency",
                    models.CharField(max_length=50, verbose_name="计价货币"),
                ),
                ("price", models.FloatField(verbose_name="价格")),
                ("scrap_price", models.FloatField(verbose_name="废料价格")),
                ("price_update_date", models.DateField(verbose_name="价格更新日期")),
            ],
            options={
                "verbose_name": "组装材料价格",
                "verbose_name_plural": "组装材料价格",
                "abstract": False,
            },
        ),
    ]
