# Generated by Django 4.2.4 on 2023-09-20 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "material_price_info",
            "0008_chongyangmaterialprice_penhuimaterialprice_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChongyangMaterialPrice",
        ),
        migrations.DeleteModel(
            name="DianduMaterialPrice",
        ),
        migrations.DeleteModel(
            name="PenhuiMaterialPrice",
        ),
        migrations.DeleteModel(
            name="PentuMaterialPrice",
        ),
        migrations.DeleteModel(
            name="QiegeMaterialPrice",
        ),
        migrations.DeleteModel(
            name="ShuamaoMaterialPrice",
        ),
        migrations.DeleteModel(
            name="SuliaoMaterialPrice",
        ),
        migrations.DeleteModel(
            name="TangjinMaterialPrice",
        ),
        migrations.DeleteModel(
            name="YinshuaMaterialPrice",
        ),
        migrations.DeleteModel(
            name="ZhusuMaterialPrice",
        ),
        migrations.DeleteModel(
            name="ZuzhuangMaterialPrice",
        ),
        migrations.AlterModelOptions(
            name="chuizhongmaterialprice",
            options={"verbose_name": "材料价格", "verbose_name_plural": "材料价格"},
        ),
    ]
