# Generated by Django 4.2.4 on 2023-09-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material_price_info", "0009_delete_chongyangmaterialprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chuizhongmaterialprice",
            name="categories",
            field=models.CharField(default="垂重", max_length=100, verbose_name="类别"),
            preserve_default=False,
        ),
    ]
