# Generated by Django 4.2.4 on 2023-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material_price_info", "0011_rename_chuizhongmaterialprice_materialprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialprice",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
