# Generated by Django 4.2.4 on 2023-08-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=100)),
                ("part_number", models.CharField(max_length=100)),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("gross_weight", models.FloatField(blank=True, null=True)),
                ("net_weight", models.FloatField(blank=True, null=True)),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "material_grade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("supplier", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
