# Generated by Django 4.2.4 on 2023-08-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "产品信息", "verbose_name_plural": "产品信息"},
        ),
        migrations.AlterField(
            model_name="product",
            name="gross_weight",
            field=models.FloatField(blank=True, null=True, verbose_name="零件毛重（克）"),
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="零件尺寸高（mm）"),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.FloatField(blank=True, null=True, verbose_name="零件尺寸长（mm）"),
        ),
        migrations.AlterField(
            model_name="product",
            name="material_grade",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="材料牌号"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="material_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="材料名称"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="net_weight",
            field=models.FloatField(blank=True, null=True, verbose_name="零件净重（克）"),
        ),
        migrations.AlterField(
            model_name="product",
            name="part_name",
            field=models.CharField(max_length=100, verbose_name="采购零件"),
        ),
        migrations.AlterField(
            model_name="product",
            name="part_number",
            field=models.CharField(max_length=100, verbose_name="零件编号"),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="供应商"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.FloatField(blank=True, null=True, verbose_name="零件尺寸宽（mm）"),
        ),
    ]
