# Generated by Django 4.2.4 on 2023-08-24 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_info",
            "0002_alter_product_options_alter_product_gross_weight_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "垂重产品信息", "verbose_name_plural": "垂重产品信息"},
        ),
    ]
