# Generated by Django 4.2.4 on 2023-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_info", "0006_alter_product_annual_demand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="annual_demand",
            field=models.IntegerField(
                blank=True, default=-1, null=True, verbose_name="年需求量 （件/年)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="management_fee_percentage",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="管理费用 (%)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="profit_margin_percentage",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="利润率 (%)"
            ),
        ),
    ]
