# Generated by Django 4.2.4 on 2023-09-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_info", "0008_alter_product_annual_demand_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "产品信息", "verbose_name_plural": "产品信息"},
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.CharField(default="垂", max_length=255, verbose_name="类别"),
            preserve_default=False,
        ),
    ]
