# Generated by Django 4.2.4 on 2023-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_info", "0010_alter_product_cartons_per_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
