# Generated by Django 4.2.4 on 2023-08-24 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"verbose_name": "垂重供应商信息", "verbose_name_plural": "垂重供应商信息"},
        ),
    ]
