# Generated by Django 4.2.4 on 2023-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_info", "0002_alter_vendor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="update_date",
            field=models.DateField(blank=True, null=True, verbose_name="价格更新日期"),
        ),
    ]
