# Generated by Django 4.2.4 on 2023-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_info", "0003_vendor_update_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"verbose_name": "供应商信息", "verbose_name_plural": "供应商信息"},
        ),
        migrations.AddField(
            model_name="vendor",
            name="categories",
            field=models.CharField(default="垂重", max_length=100, verbose_name="供应商类别"),
            preserve_default=False,
        ),
    ]
