# Generated by Django 4.2.4 on 2023-09-20 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_info", "0004_alter_vendor_options_vendor_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"verbose_name": "供应商", "verbose_name_plural": "供应商"},
        ),
    ]
