# Generated by Django 4.2.4 on 2023-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_info", "0005_alter_vendor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
