# Generated by Django 4.2.4 on 2023-10-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_info", "0007_alter_vendor_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="update_date",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="价格更新日期"
            ),
        ),
    ]
