# Generated by Django 4.2.4 on 2023-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("field_name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("CharField", "CharField"),
                            ("IntegerField", "IntegerField"),
                        ],
                        max_length=50,
                    ),
                ),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
